fix: SDL Convert BGR to RGB on Linux
cpp-sc2/cpp-sc2 pull request #117
Opened 2022-08-10 14:10 UTC by danielvschoor

On Linux, the binary produces the render data in a BGR format and on Windows (and maybe Mac) it's produced as RGB. This PR changes the SDL surface to render BGR on Linux

2022-08-10 16:24 UTC, alkurbatov commented
Thanks! I'll check on OS X and merge if everything is ok.

2022-08-10 19:59 UTC, alkurbatov requested changes

2022-08-10 19:59 UTC, alkurbatov commented on src/sc2renderer/sc2_renderer.cc
> +    SDL_Surface *surface = SDL_CreateRGBSurfaceWithFormatFrom((void *) bytes, width, height, 24, 3 * width,
Style: Please, follow style used in this file. Currently pointer declaration style is different.

2022-08-10 19:59 UTC, alkurbatov commented on src/sc2renderer/sc2_renderer.cc
> +#ifdef linux
Please use `#if defined(__linux__)`.
This is again mostly for style reasons as this way is used to check target system.

2022-08-10 20:00 UTC, alkurbatov commented
Could you please provide an example image of what should be shown?
So far with both ways on OS X I see two windows: one with a game (map + screen) and another one is pure black.
I wonder which part this change affects.

2022-08-10 20:04 UTC, danielvschoor commented
> Could you please provide an example image of what should be shown?
> So far with both ways on OS X I see two windows: one with a game (map + screen) and another one is pure black.
> I wonder which of the windows this patch affects.

It should only show one screen with both the minimap and the game inside. This might be an OS X specific issue, but not sure what could cause it

2022-08-10 20:35 UTC, danielvschoor commented
![image](https://user-images.githubusercontent.com/43602193/184014892-3cda4a52-484b-429d-949d-7c7c0a8f2bb6.png)

Just one screen on Linux^^

2022-08-11 08:06 UTC, alkurbatov commented
I see. The second window spawned by the renderer example which I used to check the patch.
I'll check it again, perhaps I can spot difference in these two lines. Just curios.

Meanwhile, please squash the commits.

2022-08-11 08:07 UTC, alkurbatov commented on src/sc2renderer/sc2_renderer.cc
> +    SDL_Surface* surface = SDL_CreateRGBSurfaceWithFormatFrom((void *) bytes, width, height, 24, 3 * width,
`(void *) bytes` -> `(void*)bytes`

2022-08-11 09:05 UTC, alkurbatov commented
AT least on OS X there are no visible difference in both of these strings, lets keep the idea and apply the change only for linux. Please, fix minor style issues and I'll merge.

2022-08-14 13:29 UTC, alkurbatov commented on src/sc2renderer/sc2_renderer.cc
> +    SDL_Surface* surface = SDL_CreateRGBSurfaceWithFormatFrom((void *) bytes, width, height, 24, 3 * width,
Ok, from what I've found this is a shorter form (i.e. without pixels) of the original SDL_CreateRGBSurface, so there is no need in defined guards, we should use it on all platforms or should correct the original pixels mask.

2023-10-14 11:17 UTC, alkurbatov commented
Closed in favor of #135

2023-10-14 11:17 UTC, closed without merging